# Form implementation generated from reading ui file 'add_products.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class AddForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 313)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(150, 20, 191, 41))
        self.label.setObjectName("label")
        self.pushButton_back_add_produc = QtWidgets.QPushButton(parent=Form)
        self.pushButton_back_add_produc.setGeometry(QtCore.QRect(360, 280, 101, 21))
        self.pushButton_back_add_produc.setStyleSheet("background-color: #67BA80")
        self.pushButton_back_add_produc.setObjectName("pushButton_back_add_produc")
        self.lineEdit_name_furniture = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_name_furniture.setGeometry(QtCore.QRect(20, 80, 113, 20))
        self.lineEdit_name_furniture.setStyleSheet("background-color: #F4E8D3 ")
        self.lineEdit_name_furniture.setText("")
        self.lineEdit_name_furniture.setObjectName("lineEdit_name_furniture")
        self.comboBox_material = QtWidgets.QComboBox(parent=Form)
        self.comboBox_material.setGeometry(QtCore.QRect(280, 80, 181, 22))
        self.comboBox_material.setStyleSheet("background-color: #F4E8D3 ")
        self.comboBox_material.setObjectName("comboBox_material")
        self.lineEdit_min_price = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_min_price.setGeometry(QtCore.QRect(20, 120, 171, 31))
        self.lineEdit_min_price.setStyleSheet("background-color: #F4E8D3 ")
        self.lineEdit_min_price.setObjectName("lineEdit_min_price")
        self.lineEdit_description = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_description.setGeometry(QtCore.QRect(20, 200, 131, 41))
        self.lineEdit_description.setStyleSheet("background-color: #F4E8D3 ")
        self.lineEdit_description.setObjectName("lineEdit_description")
        self.lineEdit_article = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_article.setGeometry(QtCore.QRect(20, 160, 131, 21))
        self.lineEdit_article.setStyleSheet("background-color: #F4E8D3 ")
        self.lineEdit_article.setObjectName("lineEdit_article")
        self.pushButton_add_products = QtWidgets.QPushButton(parent=Form)
        self.pushButton_add_products.setGeometry(QtCore.QRect(180, 260, 101, 31))
        self.pushButton_add_products.setStyleSheet("background-color: #67BA80")
        self.pushButton_add_products.setObjectName("pushButton_add_products")
        self.comboBox_model = QtWidgets.QComboBox(parent=Form)
        self.comboBox_model.setGeometry(QtCore.QRect(280, 120, 181, 22))
        self.comboBox_model.setStyleSheet("background-color: #F4E8D3 ")
        self.comboBox_model.setObjectName("comboBox_model")
        self.comboBox_type_product = QtWidgets.QComboBox(parent=Form)
        self.comboBox_type_product.setGeometry(QtCore.QRect(280, 160, 181, 22))
        self.comboBox_type_product.setStyleSheet("background-color: #F4E8D3 ")
        self.comboBox_type_product.setObjectName("comboBox_type_product")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Добавить мебель</span></p></body></html>"))
        self.pushButton_back_add_produc.setText(_translate("Form", "назад"))
        self.lineEdit_name_furniture.setPlaceholderText(_translate("Form", "введите имя"))
        self.lineEdit_min_price.setPlaceholderText(_translate("Form", "введите мин цену"))
        self.lineEdit_description.setPlaceholderText(_translate("Form", "введите описание"))
        self.lineEdit_article.setPlaceholderText(_translate("Form", "введите артикул"))
        self.pushButton_add_products.setText(_translate("Form", "добавить"))
