# Form implementation generated from reading ui file 'change_pr.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_product(object):
    def setupUi(self, add_product):
        add_product.setObjectName("add_product")
        add_product.resize(475, 313)
        add_product.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(parent=add_product)
        self.label.setGeometry(QtCore.QRect(150, 20, 191, 41))
        self.label.setObjectName("label")
        self.pushButton_back_change = QtWidgets.QPushButton(parent=add_product)
        self.pushButton_back_change.setGeometry(QtCore.QRect(360, 280, 101, 21))
        self.pushButton_back_change.setStyleSheet("background-color: #67BA80")
        self.pushButton_back_change.setObjectName("pushButton_back_change")
        self.lineEdit_name_furniture = QtWidgets.QLineEdit(parent=add_product)
        self.lineEdit_name_furniture.setGeometry(QtCore.QRect(20, 80, 113, 20))
        self.lineEdit_name_furniture.setStyleSheet("background-color: #F4E8D3 ")
        self.lineEdit_name_furniture.setText("")
        self.lineEdit_name_furniture.setObjectName("lineEdit_name_furniture")
        self.comboBox_material = QtWidgets.QComboBox(parent=add_product)
        self.comboBox_material.setGeometry(QtCore.QRect(280, 80, 181, 22))
        self.comboBox_material.setStyleSheet("background-color: #F4E8D3 ")
        self.comboBox_material.setObjectName("comboBox_material")
        self.lineEdit_min_price = QtWidgets.QLineEdit(parent=add_product)
        self.lineEdit_min_price.setGeometry(QtCore.QRect(20, 120, 171, 31))
        self.lineEdit_min_price.setStyleSheet("background-color: #F4E8D3 ")
        self.lineEdit_min_price.setObjectName("lineEdit_min_price")
        self.lineEdit_description = QtWidgets.QLineEdit(parent=add_product)
        self.lineEdit_description.setGeometry(QtCore.QRect(20, 200, 131, 41))
        self.lineEdit_description.setStyleSheet("background-color: #F4E8D3 ")
        self.lineEdit_description.setObjectName("lineEdit_description")
        self.lineEdit_article = QtWidgets.QLineEdit(parent=add_product)
        self.lineEdit_article.setGeometry(QtCore.QRect(20, 160, 131, 21))
        self.lineEdit_article.setStyleSheet("background-color: #F4E8D3 ")
        self.lineEdit_article.setObjectName("lineEdit_article")
        self.pushButton_change_products = QtWidgets.QPushButton(parent=add_product)
        self.pushButton_change_products.setGeometry(QtCore.QRect(110, 260, 101, 31))
        self.pushButton_change_products.setStyleSheet("background-color: #67BA80")
        self.pushButton_change_products.setObjectName("pushButton_change_products")
        self.comboBox_model = QtWidgets.QComboBox(parent=add_product)
        self.comboBox_model.setGeometry(QtCore.QRect(280, 120, 181, 22))
        self.comboBox_model.setStyleSheet("background-color: #F4E8D3 ")
        self.comboBox_model.setObjectName("comboBox_model")
        self.comboBox_type_product = QtWidgets.QComboBox(parent=add_product)
        self.comboBox_type_product.setGeometry(QtCore.QRect(280, 160, 181, 22))
        self.comboBox_type_product.setStyleSheet("background-color: #F4E8D3 ")
        self.comboBox_type_product.setObjectName("comboBox_type_product")
        self.pushButton_delete_products = QtWidgets.QPushButton(parent=add_product)
        self.pushButton_delete_products.setGeometry(QtCore.QRect(240, 260, 101, 31))
        self.pushButton_delete_products.setStyleSheet("background-color: #67BA80")
        self.pushButton_delete_products.setObjectName("pushButton_delete_products")

        self.retranslateUi(add_product)
        QtCore.QMetaObject.connectSlotsByName(add_product)

    def retranslateUi(self, add_product):
        _translate = QtCore.QCoreApplication.translate
        add_product.setWindowTitle(_translate("add_product", "добавить продукт"))
        self.label.setText(_translate("add_product", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Редактировать мебель</span></p></body></html>"))
        self.pushButton_back_change.setText(_translate("add_product", "назад"))
        self.lineEdit_name_furniture.setPlaceholderText(_translate("add_product", "введите имя"))
        self.lineEdit_min_price.setPlaceholderText(_translate("add_product", "введите мин цену"))
        self.lineEdit_description.setPlaceholderText(_translate("add_product", "введите описание"))
        self.lineEdit_article.setPlaceholderText(_translate("add_product", "введите артикул"))
        self.pushButton_change_products.setText(_translate("add_product", "редактировать"))
        self.pushButton_delete_products.setText(_translate("add_product", "удалить"))
