# Form implementation generated from reading ui file 'products.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Products(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(618, 391)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/КОД 09.02.07-2-2025 Приложения к образцу задания Том 1 (1)/Ресурсы/Мастер пол.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(250, 20, 121, 31))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 80, 581, 251))
        self.listWidget.setStyleSheet("background-color: #F4E8D3 ")
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 340, 141, 31))
        self.pushButton.setStyleSheet("background-color: #67BA80")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 340, 151, 31))
        self.pushButton_2.setStyleSheet("background-color: #67BA80")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 71, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/КОД 09.02.07-2-2025 Приложения к образцу задания Том 1 (1)/Ресурсы/Мастер пол.ico"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Мастер пол</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "добавить мебель"))
        self.pushButton_2.setText(_translate("Form", "просмотр списка цехов"))
