# Form implementation generated from reading ui file 'workshop.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_workshop(object):
    def setupUi(self, workshop):
        workshop.setObjectName("workshop")
        workshop.resize(548, 406)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/КОД 09.02.07-2-2025 Приложения к образцу задания Том 1 (1)/Ресурсы/Мастер пол.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        workshop.setWindowIcon(icon)
        workshop.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(parent=workshop)
        self.label.setGeometry(QtCore.QRect(170, 20, 201, 61))
        self.label.setObjectName("label")
        self.listWidget_workshop = QtWidgets.QListWidget(parent=workshop)
        self.listWidget_workshop.setGeometry(QtCore.QRect(30, 120, 461, 231))
        self.listWidget_workshop.setStyleSheet("background-color: #F4E8D3 ")
        self.listWidget_workshop.setObjectName("listWidget_workshop")
        self.pushButton_back_worlshop = QtWidgets.QPushButton(parent=workshop)
        self.pushButton_back_worlshop.setGeometry(QtCore.QRect(440, 360, 81, 31))
        self.pushButton_back_worlshop.setStyleSheet("background-color: #67BA80 ")
        self.pushButton_back_worlshop.setObjectName("pushButton_back_worlshop")
        self.label_2 = QtWidgets.QLabel(parent=workshop)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 121, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox_products_workshop = QtWidgets.QComboBox(parent=workshop)
        self.comboBox_products_workshop.setGeometry(QtCore.QRect(160, 90, 161, 22))
        self.comboBox_products_workshop.setObjectName("comboBox_products_workshop")

        self.retranslateUi(workshop)
        QtCore.QMetaObject.connectSlotsByName(workshop)

    def retranslateUi(self, workshop):
        _translate = QtCore.QCoreApplication.translate
        workshop.setWindowTitle(_translate("workshop", "просмотр списка цехов"))
        self.label.setText(_translate("workshop", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">просмотр списка</span></p><p align=\"center\"><span style=\" font-size:14pt;\">цехов</span></p></body></html>"))
        self.pushButton_back_worlshop.setText(_translate("workshop", "назад"))
        self.label_2.setText(_translate("workshop", "наименование цеха"))
